############################################################
#
# Arlo Sensor
#
############################################################

- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
