############################################################
#
# Nest Sensor
#
############################################################

- platform: nest
  monitored_conditions:
    - 'operation_mode'
    - 'temperature'
    - 'target'