############################################################
#
# Home Assistant Binary Sensors
#
############################################################

- platform: octoprint
  monitored_conditions:
    - Printing
    - Printing Error
