############################################################
#
# Home Assistant Z-Wave Configs
#
############################################################

light.12724_island_dimmer_switch_level_14_0:
  refresh_value: True
  delay: 1

light.ge_12724_3way_dimmer_switch_level_15_0:
  refresh_value: True
  delay: 1

light.linear_lb60z1_dimmable_led_light_bulb_level_2_0:
  refresh_value: True
  delay: 1

light.linear_lb60z1_dimmable_led_light_bulb_level_5_0:
  refresh_value: True
  delay: 1